# Generated by Django 3.1.5 on 2021-01-11 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Auth_User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jwt_auth_login_register.role')),
            ],
        ),
    ]
