# Generated by Django 3.1.5 on 2021-01-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0002_auto_20210106_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
