# Generated by Django 3.1.5 on 2021-01-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0004_auto_20210106_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='uuid',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
