# Generated by Django 3.1.5 on 2021-02-02 05:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0008_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='info',
        ),
        migrations.AddField(
            model_name='box',
            name='back_texture',
            field=models.ImageField(default='white.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='box',
            name='bottom_texture',
            field=models.ImageField(default='red.jpg', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='box',
            name='depth',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(800), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='box',
            name='front_texture',
            field=models.ImageField(default='blue.png', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='box',
            name='height',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(800), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='box',
            name='left_texture',
            field=models.ImageField(default='green.png', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='box',
            name='name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='box',
            name='right_texture',
            field=models.ImageField(default='yellow.png', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='box',
            name='top_texture',
            field=models.ImageField(default='pink.png', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jwt_auth_login_register.user'),
        ),
        migrations.AddField(
            model_name='box',
            name='width',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(800), django.core.validators.MinValueValidator(50)]),
        ),
    ]
