# Generated by Django 3.1.5 on 2021-02-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0009_auto_20210202_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='back_texture',
            field=models.ImageField(default='uploads/white.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='box',
            name='bottom_texture',
            field=models.ImageField(default='uploads/red.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='box',
            name='front_texture',
            field=models.ImageField(default='uploads/blue.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='box',
            name='left_texture',
            field=models.ImageField(default='uploads/green.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='box',
            name='right_texture',
            field=models.ImageField(default='uploads/yellow.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='box',
            name='top_texture',
            field=models.ImageField(default='uploads/pink.png', upload_to='uploads/'),
        ),
    ]
