# Generated by Django 3.1.5 on 2021-02-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0010_auto_20210202_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='preview_image',
            field=models.ImageField(default='uploads/red.jpg', upload_to='uploads/'),
        ),
    ]
