# Generated by Django 3.1.5 on 2021-02-09 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0011_box_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='back_texture',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='bottom_texture',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='depth',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(1500), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='front_texture',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(1500), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='left_texture',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='preview_image',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='right_texture',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='top_texture',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(1500), django.core.validators.MinValueValidator(50)]),
        ),
    ]
