# Generated by Django 3.1.5 on 2021-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0012_auto_20210209_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='preview_image',
            field=models.ImageField(default='uploads/kraft.jpg', upload_to='uploads/'),
        ),
    ]
