# Generated by Django 3.1.5 on 2021-02-16 09:09

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0013_auto_20210209_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=50)),
                ('material_price', models.FloatField()),
                ('decoration_price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='box',
            name='depth',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(400)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(400)]),
        ),
        migrations.AlterField(
            model_name='box',
            name='width',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(400)]),
        ),
    ]
