# Generated by Django 3.1.5 on 2021-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0015_auto_20210216_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxprice',
            name='decoration_price',
            field=models.FloatField(verbose_name='decoration price per m^2 in INR'),
        ),
        migrations.AlterField(
            model_name='boxprice',
            name='material_price',
            field=models.FloatField(verbose_name='Material Price per kg in INR'),
        ),
    ]
