# Generated by Django 3.1.5 on 2021-02-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0016_auto_20210216_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='material',
            field=models.CharField(default='kraft', max_length=50),
        ),
    ]
