# Generated by Django 3.1.5 on 2021-02-23 09:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0017_box_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jwt_auth_login_register.box')),
            ],
        ),
    ]
