# Generated by Django 3.1.5 on 2021-03-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0020_auto_20210303_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jwt_auth_login_register.user'),
        ),
    ]
