# Generated by Django 3.1.5 on 2021-03-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0023_auto_20210323_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
