# Generated by Django 3.1.5 on 2021-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0024_auto_20210323_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='../static/images/default_pic.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='box',
            name='preview_image',
            field=models.ImageField(default='../static/images/kraft.jpg', upload_to='uploads/'),
        ),
    ]
