# Generated by Django 3.1.5 on 2021-03-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth_login_register', '0025_auto_20210324_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='jwt_auth_login_register.purchase'),
        ),
    ]
